#!/usr/bin/env bash
# Adds an extensionless -> .html 301 for every /parts/ page.
#
# Netlify resolves /parts/octg-casing to the .html file and serves it with a
# 200, so every family page had two live URLs. The rest of the site has had
# forced 301s for this since the canonicalisation pass; the 243 pages added
# later were never covered, so this was 243 duplicate pairs.
#
# Written as explicit per-page rules rather than a :placeholder wildcard on
# purpose. A rule like `/parts/:slug /parts/:slug.html 301!` also matches
# /parts/octg-casing.html -- slug would capture "octg-casing.html" and redirect
# it to /parts/octg-casing.html.html, breaking every real URL in the section.
# Explicit rules match the extensionless form only and cannot loop.
set -euo pipefail
marker='# ---- family reference pages: extensionless -> .html ----'
# drop any previous block so this is re-runnable
if grep -qF "$marker" _redirects; then
  awk -v m="$marker" 'index($0,m){skip=1} skip && /^$/{skip=0; next} !skip' _redirects > _r.tmp && mv _r.tmp _redirects
fi
{
  echo ""
  echo "$marker"
  echo "# Generated by scripts/gen-parts-redirects.sh -- do not hand-edit."
  for f in parts/*.html; do
    s=$(basename "$f" .html)
    printf '/parts/%-58s /parts/%s.html   301!\n' "$s" "$s"
  done
} >> _redirects
echo "  rules written: $(grep -c '^/parts/' _redirects)"
