#!/usr/bin/env bash
# Regenerates _redirects from the actual page list.
#
# Run from the repo root after adding or removing a page:
#   bash scripts/gen-redirects.sh
#
# See the header it writes into _redirects for why the direction is
# extensionless -> .html rather than the other way round.
set -euo pipefail
cd "$(dirname "$0")/.."

{
cat <<'HDR'
# VOLTFIELD -- URL canonicalisation.
#
# Netlify serves BOTH /page and /page.html with a 200 and no redirect, so every
# page had two live URLs. Verified against production before writing this file:
# neither form redirected, which also means Netlify's "Pretty URLs" asset
# optimisation is OFF -- if that is ever switched ON it will 301 .html to
# extensionless and fight these rules into a loop. Leave it off.
#
# Direction: extensionless -> .html, NOT the other way round. The site is
# already entirely consistent on .html -- internal links, canonical tags and
# sitemap entries -- and Google has indexed those as canonical. Flipping to
# extensionless would mean rewriting all of that and asking Google to
# re-process every URL, for no ranking benefit: URL extensions are not a
# ranking factor. Redirecting the duplicate at the edge achieves the same
# de-duplication at a fraction of the risk.
#
# The `!` is required. Without it Netlify serves the extensionless twin from
# the .html file directly and a non-forced redirect never fires.
#
# Legacy URL, kept as a real 301 rather than the JS/meta-refresh stub it used
# to be: a client-side redirect passes less signal than a server one and costs
# a round trip plus a render. The old voltfield-home.html has been deleted.
/voltfield-home                     /                                       301!
/voltfield-home.html                /                                       301!

# Generated by scripts/gen-redirects.sh -- do not hand-edit.

HDR

# root pages, then one level of category subdirectories
for f in *.html data-centers/*.html; do
  base="${f%.html}"
  # skip if the directory glob did not match anything
  [ -e "$f" ] || continue
  # index is the root; 404 is served by Netlify's own not-found handling
  [ "$base" = "index" ] && continue
  [ "$base" = "404" ] && continue
  printf '/%-34s /%-38s 301!\n' "$base" "$f"
done
} > _redirects

echo "wrote _redirects with $(grep -c '301!' _redirects) rules"
