#!/usr/bin/env bash
# Regenerates the extensionless -> .html rules in _redirects from the actual
# page list.
#
# Run from the repo root after adding or removing a page:
#   bash scripts/gen-redirects.sh
#
# Only the block between the BEGIN/END generated markers is rewritten.
# Everything else in _redirects -- the header, legacy aliases, the repo-file
# blocks, retired commerce and /parts/ mappings -- is hand-maintained and kept
# byte for byte. (An earlier version rewrote the whole file, which by the time
# it was next run would have deleted ~500 of those rules.)
#
# See the header of _redirects for why the direction is extensionless -> .html
# rather than the other way round.
set -euo pipefail
cd "$(dirname "$0")/.."

BEGIN='# ---- BEGIN generated by scripts/gen-redirects.sh'
END='# ---- END generated ----'

grep -q "^$BEGIN" _redirects || { echo "BEGIN marker missing from _redirects" >&2; exit 1; }
grep -q "^$END" _redirects   || { echo "END marker missing from _redirects" >&2; exit 1; }

gen="$(mktemp)"
trap 'rm -f "$gen"' EXIT

# root pages, then the category subdirectories that hold site pages
for f in *.html data-centers/*.html battery-storage/*.html renewables/*.html calculators/*.html; do
  # skip if a directory glob did not match anything
  [ -e "$f" ] || continue
  base="${f%.html}"
  # index is the root; 404 is served by Netlify's own not-found handling
  [ "$base" = "index" ] && continue
  [ "$base" = "404" ] && continue
  printf '/%-34s /%-38s 301!\n' "$base" "$f"
done > "$gen"

awk -v begin="$BEGIN" -v end="$END" -v gen="$gen" '
  index($0, begin) == 1 { print; while ((getline line < gen) > 0) print line; skip = 1; next }
  index($0, end) == 1   { skip = 0 }
  !skip
' _redirects > _redirects.tmp
mv _redirects.tmp _redirects

echo "wrote $(wc -l < "$gen") generated rules; _redirects has $(grep -c '301!' _redirects) rules in total"
